---
{
   "kind": "pipeline",
   "name": "prod_image_amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "prod_image",
         "privileged": true,
         "settings": {
            "build_args": [
               "DEBIAN_VERSION=bookworm",
               "RBLDNSD_VERSION=${DRONE_SEMVER_SHORT}"
            ],
            "dockerfile": "Dockerfile",
            "label_schema": [
               "docker.dockerfile=Dockerfile"
            ],
            "password": {
               "from_secret": "docker_password"
            },
            "repo": "rspamd/rbldnsd",
            "tags": [
               "latest-amd64"
            ],
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "branch": {
         "include": [
            "main"
         ]
      },
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "prod_image_arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "prod_image",
         "privileged": true,
         "settings": {
            "build_args": [
               "DEBIAN_VERSION=bookworm",
               "RBLDNSD_VERSION=${DRONE_SEMVER_SHORT}"
            ],
            "dockerfile": "Dockerfile",
            "label_schema": [
               "docker.dockerfile=Dockerfile"
            ],
            "password": {
               "from_secret": "docker_password"
            },
            "repo": "rspamd/rbldnsd",
            "tags": [
               "latest-arm64"
            ],
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "branch": {
         "include": [
            "main"
         ]
      },
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "prod_image_amd64",
      "prod_image_arm64"
   ],
   "kind": "pipeline",
   "name": "multiarch_prod_image",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "multiarch_image",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "tags": [
               "${DRONE_SEMVER_SHORT}",
               "${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "rspamd/rbldnsd:latest",
            "template": "rspamd/rbldnsd:latest-ARCH",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "branch": {
         "include": [
            "main"
         ]
      },
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "hmac": "13eb6f88390cb01ca8262ab02ef3c2db81f93a0da5eb6196c30314f28d0679e1",
   "kind": "signature"
}
...
